import test from 'node:test';
import assert from 'node:assert/strict';
import { createWorld,tick } from '../src/simulation.js';
import { seedPopulation,profile,apartmentIds,activateHousehold,resident,POPULATION } from '../src/population.js';
import {ensureLife,beginAction} from "../src/life.js";
import {decisionNetwork} from '../src/decisions.js';
import {encode,decode} from '../src/persistence.js';
const view={speed:0,angle:.65,zoom:1,panX:0,panY:15,selected:50000000};
test('census reaches fifty million without allocating fifty million agents',()=>{const w=seedPopulation(createWorld(42),true);assert.equal(w.population.total,POPULATION);assert.equal(w.citizens.length,240);assert.deepEqual(profile(50000000,42),profile(50000000,42));assert.equal(profile(50000000,42).home.building,25000);assert.throws(()=>profile(50000001));});
test('family and apartment references are reciprocal and stable',()=>{const ids=apartmentIds(25000,25,20);assert.deepEqual(ids,[49999997,49999998,49999999,50000000]);const p=profile(ids[0],4),child=profile(ids[2],4);assert.equal(profile(p.partner,4).partner,p.id);assert.ok(child.parents.includes(p.id));assert.ok(p.children.includes(child.id));assert.deepEqual(child.home,p.home);});
test('activation and save preserve virtual references and exact future state',()=>{const w=seedPopulation(createWorld(42),true);activateHousehold(w,50000000);assert.equal(w.citizens.length,244);assert.ok(resident(w,50000000).active);for(let i=0;i<100;i++)tick(w);const copy=decode(encode(w,view)).world;for(let i=0;i<300;i++){tick(w);tick(copy);}assert.deepEqual(w,copy);assert.ok(encode(w,view).length<3000000);});
test('displayed network drives actual decisions and keeps children out of work',()=>{const w=seedPopulation(createWorld(42),true);const a=w.citizens[0];ensureLife(a,()=>.5);beginAction(w,a,"Play",()=>.5);assert.deepEqual(a.scores,decisionNetwork(w,a).outputs.map(n=>[n.name,n.value]));const child=w.citizens[2];assert.equal(decisionNetwork(w,child).outputs.find(n=>n.name==='Work').value,0);});
test('invalid virtual save references and appearance are rejected',()=>{const w=seedPopulation(createWorld(42),true);w.citizens[0].partner=60000000;assert.throws(()=>decode(encode(w,view)));w.citizens[0].partner=2;w.citizens[0].skin='url(evil)';assert.throws(()=>decode(encode(w,view)));});
