import { ACTIONS,forward } from './brain.js';
export function decisionNetwork(world,a){
 const hour=Math.floor(world.minutes%1440/60),l=a.life||{},school=a.age>=5&&a.age<18&&hour>=8&&hour<15,sick=!!a.illness;
 const entries=[['hunger','Hunger',a.hunger],['fatigue','Fatigue',1-a.energy],['lonely','Loneliness',l.loneliness??.3],['bored','Boredom',l.boredom??.3],['stress','Stress',l.stress??.15],['ill','Illness',sick?1:0],['lowMoney','Low funds',Math.max(0,1-a.wealth/100)],['ambition','Ambition',a.drives.ambition],['empathy','Empathy',a.drives.empathy],['analysis','Curiosity',a.drives.analysis],['caution','Caution',a.drives.caution],['child','Under 18',a.age<18?1:0],['school','School time',school?1:0],['family','Family time',hour>=18&&hour<21?1:.1],['night','Night',hour<7||hour>=22?1:0],['healthRisk','Health risk',1-a.health]];
 const x=entries.map(e=>e[2]),model=a.brain?forward(a.brain,x):{h:Array(8).fill(0),o:Array(10).fill(0)};
 const bias=[a.hunger*2.5,(1-a.energy)*2.4+(hour<7||hour>=22?.4:0)+(sick?.4:0),.18+a.drives.ambition*.35+Math.max(0,1-a.wealth/100)*.65,(l.loneliness??.3)*1.8+a.drives.empathy*.2,(l.boredom??.3)*.75+a.drives.analysis*.2,(l.loneliness??.3)*.8+(hour>=18&&hour<21?.7:0),school?1.25:0,(l.boredom??.3)*1.65+(l.stress??.15)*.4,(l.boredom??.3)*.6+a.drives.analysis*.65,sick?(a.illness.treated?.15:1.3)+(1-a.health):Math.max(0,.7-a.health)];
 const outputs=ACTIONS.map((name,k)=>{const last=l.recent?.[name],novelty=last===undefined?.12:Math.min(.12,(world.minutes-last)/14400),repeat=last!==undefined?Math.max(0,1-(world.minutes-last)/360)*.5:0;let value=Math.max(0,bias[k]+model.o[k]+novelty-repeat);if((name==='Work'&&a.age<18)||(name==='School'&&!school)||(name==='Family'&&!a.partner&&!a.parents.length&&!a.children.length))value=0;return {weights:Object.fromEntries(model.h.map((_,j)=>[`h${j}`,a.brain?.w2[j*10+k]||0])),name,key:`h${k%8}`,value,instinct:bias[k],learned:model.o[k],novelty:novelty-repeat};}).sort((a,b)=>b.value-a.value);
 const inputs=entries.map(([id,label,value])=>({id,label,value})),hidden=model.h.map((value,j)=>({id:`h${j}`,label:`Learned ${j+1}`,value,weights:Object.fromEntries(inputs.map((n,i)=>[n.id,a.brain?.w1[i*8+j]||0]))}));
 return {inputs,hidden,outputs,x};
}
