import {DISEASES} from './life.js';
import {ACTIONS} from './brain.js';
import {resident} from './population.js';
import {decisionNetwork} from './decisions.js';
import {routineFor,DISTRICTS,districtAt} from './city-life.js';
import {dateLabel} from './simulation.js';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meter=(label,value)=>`<div class="life-meter"><span>${label}</span><b>${Math.round(value*100)}%</b><i style="--fill:${Math.max(0,Math.min(100,value*100))}%"></i></div>`;
const timeInput=h=>`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.round(h%1*60)).padStart(2,'0')}`;
const slider=(key,label,v,max=100)=>`<label class="setting-slider"><span>${label}</span><input name="${key}" type="range" min="0" max="${max}" step="1" value="${Math.round(v)}"><output>${Math.round(v)}</output></label>`;
export function renderInspector(w,id,tab='mind'){
 const {person:a,active}=resident(w,id),r=routineFor(a),net=decisionNetwork(w,a),l=a.life||{},mood=l.stress>.65?'Overwhelmed':l.loneliness>.65?'Lonely':l.boredom>.65?'Restless':a.illness?'Unwell':'Settled';
 const name=id=>{try{return resident(w,id).person.name;}catch{return 'Unknown resident';}};
 const link=id=>`<button class="relationship-link" data-person="${id}">${esc(name(id))}<span>View life →</span></button>`;
 const header=`<div class="citizen-banner"><div class="portrait" style="--shirt:${a.clothes||'#58b9dd'};--skin:${a.skin||'#c58d63'}"><i></i><b></b></div><div><small>${w.player?.id===a.id?'YOUR CHARACTER':'A LIFE IN FREE CITY'} · #${id.toLocaleString()}</small><h2>${esc(a.name)}</h2><p>${Math.floor(a.age)} years · ${esc(a.role)} · ${esc(districtAt(a).name)}</p></div><button data-home>Locate ↗</button><button data-close-mind aria-label="Close citizen dashboard">✕</button></div><nav class="mind-tabs" aria-label="Citizen pages">${[['mind','Mind'],['settings','Life settings'],['people','People & society'],['history','History & home']].map(([key,label])=>`<button data-mind-tab="${key}" class="${tab===key?'selected':''}" aria-pressed="${tab===key}">${label}</button>`).join('')}<span>${active?'● LIVE':'○ VIRTUAL PROFILE'}</span></nav>`;
 const controls=`<section class="life-card resident-commands"><h3>Give a direction</h3>${active?`<label>Next activity<select id="resident-action">${ACTIONS.filter(x=>x!=='Travel'&&(a.age>=18||x!=='Theft')).map(x=>`<option>${x}</option>`).join('')}</select></label><button data-direct>Do this next</button><label>Neighborhood<select id="resident-district">${DISTRICTS.map(d=>`<option value="${d.id}" ${districtAt(a).id===d.id?'selected':''}>${d.name}</option>`).join('')}</select></label><button data-travel>Travel there</button><small>Directions override the current plan. Travel between neighborhoods is illustrative; it does not follow individual streets.</small>`:'<p>Activate this household to change its life and decisions.</p><button data-activate class="primary">Activate household</button>'}</section>`;
 let body='';
 if(tab==='mind')body=`<div class="life-layout"><div><section class="life-card thought-hero"><span class="eyebrow">RIGHT NOW</span><h2>“${esc(a.thought)}”</h2><div class="state-pills"><span>${mood}</span><span>${a.health<=0?'Deceased':esc(a.action)}</span><span>${a.brain?.lessons||0} learned experiences</span></div></section><section class="life-card"><h3>How this moment connects</h3><div class="thought-map"><div class="thought-influences"><div><small>BODY</small><strong>${a.hunger>.5?'I need food':a.energy<.4?'I need rest':'My basic needs are met'}</strong><span>${Math.round(a.hunger*100)}% hunger · ${Math.round(a.energy*100)}% energy</span></div><div><small>FEELING</small><strong>${mood}</strong><span>${Math.round((l.stress||0)*100)}% stress · ${Math.round((l.loneliness||0)*100)}% loneliness</span></div><div><small>EXPERIENCE</small><strong>${a.brain?.lessons||0} outcomes learned</strong><span>Preferences evolve from results</span></div></div><div class="decision-core"><small>CURRENT CHOICE</small><strong>${esc(a.action)}</strong><span>${l.plan?`${Math.ceil(l.plan.remaining)} activity minutes after arrival`:'Waiting for the next choice'}</span></div><div class="goal-node"><small>WHAT I AM WORKING TOWARD</small><strong>${esc(a.goal)}</strong></div></div></section><section class="life-card"><h3>Other things on my mind</h3><div class="choice-list">${net.outputs.slice(0,4).map(n=>`<div><span>${n.name}</span><i style="--fill:${Math.min(100,n.value/3*100)}%"></i><b>${n.value.toFixed(2)}</b></div>`).join('')}</div><small>Current priorities; a committed activity can continue even when priorities shift. Feelings and dialogue are simulated.</small></section></div><div><section class="life-card"><h3>Body & mood</h3><p class="illness-line">${a.illness?esc(DISEASES[a.illness.kind].name)+(a.illness.treated?' · receiving care':''):'No current illness'}</p>${meter('Health',a.health)}${meter('Energy',a.energy)}${meter('Fullness',1-a.hunger)}${meter('Company',1-(l.loneliness??.3))}${meter('Enjoyment',1-(l.boredom??.3))}</section>${controls}<section class="life-card"><h3>Learning changes</h3>${(l.adaptations||[]).slice(0,3).map(m=>`<p class="timeline-item"><small>${dateLabel(m.time)}</small>${esc(m.text)}</p>`).join('')||'<p class="muted">As experiences accumulate, changes to caution and learned preferences appear here.</p>'}<small>Bounded parameter learning. Residents do not execute new source code.</small></section></div></div>`;
 if(tab==='settings')body=`<div class="life-layout settings-layout"><form id="life-settings-form" class="life-card"><h2>Shape a daily life</h2><p>These preferences influence autonomous choices. Direct control stays with you while your character is in manual mode.</p><fieldset ${active?'':'disabled'}><legend>Rest & meals</legend><div class="settings-row"><label>Bedtime<input name="sleepStart" type="time" value="${timeInput(r.sleepStart)}" required></label><label>Sleep duration (hours)<input name="sleepHours" type="number" min="1" max="16" step=".5" value="${r.sleepHours}" required></label></div><label>Meal times, separated by commas<input name="meals" value="${r.meals.map(timeInput).join(', ')}" placeholder="08:00, 13:00, 19:00" required></label><label>Eating habit<select name="mealSize"><option value="0.7" ${r.mealSize===.7?'selected':''}>Smaller meals</option><option value="1" ${r.mealSize===1?'selected':''}>Regular meals</option><option value="1.3" ${r.mealSize===1.3?'selected':''}>Larger meals</option></select></label><legend>Skills & personality</legend>${slider('socialSkill','Social skill',r.socialSkill)}${slider('knowledge','Knowledge / research',r.knowledge)}${slider('solitude','Preference for time alone',r.solitude*100)}${slider('curiosity','Curiosity',r.curiosity*100)}${slider('risk','Risk taking',r.risk*100)}<label class="autonomy-check"><input name="autonomy" type="checkbox" ${a.autonomy!==false?'checked':''}> Choose activities autonomously between directions</label><button class="primary" type="submit">Save life settings</button><p id="life-settings-status" role="status"></p></fieldset></form><div>${controls}<section class="life-card"><h3>What changes?</h3><p>Bedtime encourages sleep. Meal times and portion size influence eating. Social skill helps conversations build trust; a preference for solitude makes time alone more rewarding.</p><p>Knowledge changes research skill. Curiosity favors learning and exploration. High risk taking and financial desperation can encourage theft, which damages trust and may incur fines.</p><p>Immediate danger and urgent physical needs can interrupt an autonomous routine.</p></section></div></div>`;
 if(tab==='people'){const relations=[...new Set([...(a.partner?[a.partner]:[]),...a.parents,...a.children,...(a.friends||[]),...Object.keys(a.relations).map(Number)])].sort((b,c)=>(a.relations[c]||0)-(a.relations[b]||0)).slice(0,15),dialogues=(w.conversations||[]).filter(c=>c.from===id||c.to===id).slice(0,12),clubs=(w.communities||[]).filter(c=>c.members.includes(id));body=`<div class="life-layout"><div><section class="life-card"><h2>Conversations</h2><p class="muted">Contextual simulated dialogue, with lasting effects on relationships.</p>${w.player&&w.player.id!==id&&active?`<form id="speak-form"><label>Say something as ${esc(name(w.player.id))}<input name="message" maxlength="240" required placeholder="Write a message…"></label><button type="submit" class="primary">Visit & talk</button><small>Your character travels to this resident before speaking.</small></form>`:''}${dialogues.map(c=>`<div class="conversation"><small>${dateLabel(c.time)} · ${esc(c.topic)}</small><p><b>${esc(name(c.from))}</b>${esc(c.text)}</p><p class="reply"><b>${esc(name(c.to))}</b>${esc(c.reply)}</p></div>`).join('')||'<div class="empty-state">A conversation has not happened yet. Choose Socialize to seek company.</div>'}</section><section class="life-card"><h3>Communities</h3>${clubs.map(c=>`<div class="community-card"><strong>${esc(c.name)}</strong><p>${esc(c.purpose)} · ${c.members.length} members</p></div>`).join('')||'<p>Trusted neighbors can form study circles and mutual-help groups through conversation.</p>'}</section></div><div><section class="life-card"><h3>Relationships</h3>${relations.map(id=>`<div class="relationship">${link(id)}<small>${a.partner===id?'Partner':a.parents.includes(id)?'Parent':a.children.includes(id)?'Child':'Connection'} · trust ${Math.round((a.relations[id]||0)*100)}</small></div>`).join('')||'<p>No relationships yet. Meet someone to begin.</p>'}</section><section class="life-card"><h3>Reputation</h3><strong>${Math.round((l.reputation||0)*100)}</strong><p>Theft and social consequences change how this resident is regarded.</p></section></div></div>`;}
 if(tab==='history')body=`<div class="life-layout"><div><section class="life-card"><h2>A life, remembered</h2>${a.memories.map(m=>`<p class="timeline-item"><small>${dateLabel(m.time)}</small>${esc(m.text)}</p>`).join('')||'<p>No lived memories yet.</p>'}</section><section class="life-card"><h3>Completed activities</h3>${(l.history||[]).map(m=>`<p class="timeline-item"><small>${dateLabel(m.time)}</small>${esc(m.text)}</p>`).join('')}</section></div><div><section class="life-card"><h3>Home</h3><p>${esc(a.home?.label||'Unassigned')}</p><p>${esc(districtAt(a.home||a).name)}</p><div class="floor-plan"><span>Living & dining</span><span>Bedroom</span><span>Kitchen</span><span>Bedroom</span><span>Bath</span></div><div class="apartment-panel"><label>Building<input id="apt-building" type="number" min="1" max="25000" value="${a.home?.building||1}"></label><label>Floor<input id="apt-floor" type="number" min="1" max="25" value="${a.home?.floor||1}"></label><label>Apartment<input id="apt-unit" type="number" min="1" max="20" value="${a.home?.unit||1}"></label><button data-apartment>Open household</button></div></section><section class="life-card"><h3>Work & money</h3><strong>${esc(a.job?.title||a.role)}</strong><p>${esc(a.job?.employer||'Community')} · ${Math.floor(a.wealth)} credits</p></section></div></div>`;
 return header+`<div class="life-content">${body}</div>`;
}
