import { resident, householdIds } from './population.js';
import { decisionNetwork } from './decisions.js';
import { dateLabel } from './simulation.js';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meter=(name,value)=>`<div class="meter"><span>${esc(name)}</span><b>${Math.round(value*100)}%</b><i><em style="width:${Math.max(0,Math.min(100,value*100))}%"></em></i></div>`;
export function networkSVG(network){
 const cols=[network.inputs,network.hidden,network.outputs.map(n=>({...n,id:n.name,label:n.name}))],xs=[110,325,535],positions={};
 cols.forEach((col,c)=>col.forEach((n,i)=>positions[n.id]=[xs[c],55+i*440/Math.max(1,col.length-1)]));
 let lines='';for(const n of network.hidden)for(const [id,w]of Object.entries(n.weights)){const [x,y]=positions[id],[xx,yy]=positions[n.id];lines+=`<path d="M${x} ${y} C${x+100} ${y} ${xx-100} ${yy} ${xx} ${yy}" stroke="${w<0?'#df797c':'#58bda3'}" opacity="${.2+Math.min(.6,Math.abs(w)*.35)}" stroke-width="${Math.abs(w)*2}"><title>${esc(id)} → ${esc(n.label)}: weight ${w}</title></path>`;}
 for(const n of network.outputs){const[x,y]=positions[n.key],[xx,yy]=positions[n.name];lines+=`<path d="M${x} ${y} C${x+100} ${y} ${xx-100} ${yy} ${xx} ${yy}" stroke="#71c9e6" opacity=".5"/>`;}
 const nodes=cols.map((col,c)=>col.map(n=>{const[x,y]=positions[n.id];return `<g><circle cx="${x}" cy="${y}" r="${c===1?15:9}" fill="${c===2&&n.name===network.outputs[0].name?'#7fe0bb':'#132c32'}" stroke="#70c3b0" stroke-width="${1+n.value*2}"/><text x="${x+(c===0?-16:20)}" y="${y-2}" text-anchor="${c===0?'end':'start'}">${esc(n.label)}</text><text class="node-value" x="${x+(c===0?-16:20)}" y="${y+12}" text-anchor="${c===0?'end':'start'}">${n.value.toFixed(2)}</text></g>`;}).join('')).join('');
 return `<svg viewBox="0 0 640 530" role="img" aria-label="Weighted decision network linking needs and traits to action priorities"><g fill="none">${lines}</g>${nodes}</svg>`;
}
export function renderInspector(world,id){const{person:a,active}=resident(world,id),network=decisionNetwork(world,a);const link=id=>{try{return `<button class="person-link" data-person="${id}">${esc(resident(world,id).person.name)} <small>#${id.toLocaleString()}</small></button>`;}catch{return '';}};const family=[...(a.partner?[[a.partner,'Partner']]:[]),...a.parents.map(id=>[id,'Parent']),...a.children.map(id=>[id,'Child'])];
 return `<div class="mind-title"><div class="portrait" style="--shirt:${a.clothes||'#67b998'};--skin:${a.skin||'#c58d63'}"><i></i><b></b></div><div><span class="eyebrow">RESIDENT #${a.id.toLocaleString()} · ${active?'LIVE SIMULATION':'VIRTUAL CENSUS RECORD'}</span><h2>${esc(a.name)}</h2><p>${Math.floor(a.age)} years · ${esc(a.role)} · Generation ${a.generation||1}</p></div><button data-close-mind aria-label="Close citizen dashboard">✕</button></div>
 <div class="mind-grid"><section class="network-panel"><h3>THE MIND</h3><p class="muted">${active?'Live weighted priorities':'Scheduled profile · illustrative priorities'}</p><div class="graph-labels"><span>SENSES & TRAITS</span><span>EVALUATION</span><span>URGES</span></div>${networkSVG(network)}<div class="goal"><small>LONG-TERM GOAL</small><p>${esc(a.goal)}</p><strong>${esc(a.action)}</strong> <span>current action</span></div><p class="muted">Connections show the actual decision weights. Red inhibits; green encourages. Rule-based simulation, not an LLM.</p></section>
 <section><article><h3>INNER VOICE</h3><blockquote>“${esc(a.thought)}”</blockquote><small>Simulation narration${active?'':' · no off-screen mind is running'}</small></article><article><h3>BODY & NEEDS</h3>${meter('Health',a.health)}${meter('Energy',a.energy)}${meter('Fullness',1-a.hunger)}</article><article><h3>CHARACTER</h3>${Object.entries(a.drives).map(([k,v])=>meter(k,v)).join('')}</article><article><h3>WORK & MONEY</h3><strong>${esc(a.job?.title||a.role)}</strong><p>${esc(a.job?.employer||'Local community')} · ${esc(a.job?.sector||'Services')}</p><p>${Math.floor(a.wealth)} credits · ${a.job?.wage||0} / working minute</p></article></section>
 <section><article><h3>SKILLS</h3>${Object.entries(a.skills||{}).map(([k,v])=>meter(k,v/100)).join('')}</article><article><h3>FAMILY & BONDS</h3>${family.map(([id,role])=>`<div class="bond"><small>${role}</small>${link(id)}</div>`).join('')||'<p>No recorded family.</p>'}${(a.friends||[]).map(id=>`<div class="bond"><small>Friend</small>${link(id)}</div>`).join('')}</article><article><h3>MEMORY VAULT</h3>${a.memories.slice(0,5).map(m=>`<p class="memory"><small>${dateLabel(m.time)}</small>${esc(m.text)}</p>`).join('')||'<p class="muted">Census residents gain memories when activated.</p>'}</article></section></div>
 <div class="apartment-panel"><div><h3>HOME / PRIVATE APARTMENT</h3><strong>${esc(a.home?.label||'Unassigned')}</strong><p>Fictional apartment allocation on the San Francisco map.</p><button data-home>Locate resident</button> ${!active?'<button data-activate>Simulate this household</button>':''}</div><div class="floor-plan"><span>Living & dining</span><span>Bedroom 1</span><span>Kitchen</span><span>Bedroom 2</span><span>Bathroom</span><span>Entry</span></div><div><label>Building <input id="apt-building" type="number" min="1" max="25000" value="${a.home?.building||1}"></label><label>Floor <input id="apt-floor" type="number" min="1" max="25" value="${a.home?.floor||1}"></label><label>Apartment <input id="apt-unit" type="number" min="1" max="20" value="${a.home?.unit||1}"></label><button data-apartment>Open household</button><small>25,000 virtual buildings · 12.5 million apartments</small></div></div>`;
}
